# Generated by Django 4.2.5 on 2023-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=128, verbose_name='password2'),
        ),
    ]
