# Generated by Django 4.2.6 on 2023-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0003_user_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
