# Generated by Django 4.2.6 on 2023-12-01 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_of_birth_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='date_of_birth'),
        ),
    ]
