# Generated by Django 4.2.7 on 2023-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_issues_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='assigned_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.contributors'),
        ),
    ]
